backend:
  name: git-gateway
  branch: main

media_folder: "images/projects"
public_folder: "/images/projects"

site_url: /
display_url: /

collections:
  - name: portfolio
    label: Portfolio
    files:
      - name: library
        label: Covers & Mockups
        file: portfolio.json
        fields:
          - label: Book Covers
            name: covers
            widget: list
            collapsed: false
            summary: "{{fields.title}}"
            fields:
              - {label: Title, name: title, widget: string}
              - {label: Genre, name: genre, widget: string, required: false}
              - {label: Author, name: author, widget: string, required: false}
              - {label: Description, name: description, widget: text, required: false}
              - {label: Cover Image, name: image, widget: image}

          - label: 3D Mockups
            name: mockups
            widget: list
            collapsed: false
            summary: "{{fields.title}}"
            fields:
              - {label: Title, name: title, widget: string}
              - {label: Type, name: genre, widget: string, default: Presentation, required: false}
              - {label: Description, name: description, widget: text, required: false}
              - {label: Mockup Image, name: image, widget: image}
